import {
  Activity,
  ArrowLeftRight,
  Banknote,
  Bell,
  Boxes,
  Briefcase,
  Bus,
  CalendarCheck,
  CalendarClock,
  Circle,
  ClipboardList,
  DoorOpen,
  FileBarChart,
  FileText,
  Files,
  Gauge,
  GraduationCap,
  HeartHandshake,
  KeyRound,
  Library,
  LineChart,
  MessageSquareWarning,
  MessagesSquare,
  MonitorPlay,
  NotebookPen,
  PackageOpen,
  Plug,
  School,
  Settings,
  ShieldCheck,
  ShieldPlus,
  ShoppingCart,
  Smartphone,
  Sparkles,
  Star,
  Target,
  TerminalSquare,
  Trophy,
  UserCog,
  UserPlus,
  Users,
  Wallet,
  Workflow,
  type LucideIcon,
} from "lucide-react";

/** Maps the manifest icon name (per module) to a lucide component. */
export const MODULE_ICONS: Record<string, LucideIcon> = {
  Activity,
  ArrowLeftRight,
  Banknote,
  Bell,
  Boxes,
  Briefcase,
  Bus,
  CalendarCheck,
  CalendarClock,
  ChartLine: LineChart,
  ClipboardList,
  DoorOpen,
  FileBarChart,
  FileText,
  Files,
  Gauge,
  GraduationCap,
  HeartHandshake,
  KeyRound,
  Library,
  MessageSquareWarning,
  MessagesSquare,
  MonitorPlay,
  NotebookPen,
  PackageOpen,
  Plug,
  School,
  Settings,
  ShieldCheck,
  ShieldPlus,
  ShoppingCart,
  Smartphone,
  Sparkles,
  Star,
  Target,
  Trophy,
  UserCog,
  UserPlus,
  Users,
  Wallet,
  Workflow,
};

export function moduleIcon(name: string): LucideIcon {
  return MODULE_ICONS[name] ?? Circle;
}

export { TerminalSquare };
